// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3sXnh3B5eNKf2--bTLVrd4prhQgH2m_4',
    appId: '1:259004684776:web:2ea1609385d4b0c27bac5d',
    messagingSenderId: '259004684776',
    projectId: 'foddly-flutter',
    authDomain: 'foddly-flutter.firebaseapp.com',
    storageBucket: 'foddly-flutter.firebasestorage.app',
    measurementId: 'G-S1NGR1PNC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaoMh-t1lt3n3ZHMUHPbwAg2tp7quafZM',
    appId: '1:259004684776:android:ce2cd1e8dc397fb37bac5d',
    messagingSenderId: '259004684776',
    projectId: 'foddly-flutter',
    storageBucket: 'foddly-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNgyvKO4ZQN9RKgXuX2kW4ZVNmq0-tDOU',
    appId: '1:259004684776:ios:0267e99461e86d2e7bac5d',
    messagingSenderId: '259004684776',
    projectId: 'foddly-flutter',
    storageBucket: 'foddly-flutter.firebasestorage.app',
    iosClientId: '259004684776-s4h2bblotkuvbhmejf8f7s5dlrr94vb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNgyvKO4ZQN9RKgXuX2kW4ZVNmq0-tDOU',
    appId: '1:259004684776:ios:0267e99461e86d2e7bac5d',
    messagingSenderId: '259004684776',
    projectId: 'foddly-flutter',
    storageBucket: 'foddly-flutter.firebasestorage.app',
    iosClientId: '259004684776-s4h2bblotkuvbhmejf8f7s5dlrr94vb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3sXnh3B5eNKf2--bTLVrd4prhQgH2m_4',
    appId: '1:259004684776:web:da68822618d929577bac5d',
    messagingSenderId: '259004684776',
    projectId: 'foddly-flutter',
    authDomain: 'foddly-flutter.firebaseapp.com',
    storageBucket: 'foddly-flutter.firebasestorage.app',
    measurementId: 'G-L68FBL0V1K',
  );
}
